"""
Django settings for SpaceZone project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-af_z0&%+c$+&6k(vxe^*zj%jt_p%iv7nw3wn%krf7t71gr^e0k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Set to True only for development

# Hosts allowed to serve this Django project

ALLOWED_HOSTS = ['localhost', '127.0.0.1','spacezone-djangopanel.onrender.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # Django REST Framework
    'rest_framework_simplejwt',  # JWT authentication
    'rest_framework_simplejwt.token_blacklist',  # Blacklist app
    'drf_spectacular',
    'accounts',  # Custom user app
    'product',
    'admin_panel',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # 'whitenoise.middleware.WhiteNoiseMiddleware',
]

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


ROOT_URLCONF = 'SpaceZone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Template directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SpaceZone.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',  # Using SQLite for development
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True  # Enable Django's translation system

USE_TZ = True  # Use timezone-aware datetimes

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework authentication settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONOpenAPIRenderer'],
}

# Custom user model
AUTH_USER_MODEL = 'accounts.CustomUserModel'

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),  # Lifetime of the Access Token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Lifetime of the Refresh Token
    'ROTATE_REFRESH_TOKENS': True,  # Issue a new refresh token each time it's used
    'BLACKLIST_AFTER_ROTATION': True,  # Blacklist the previous token after rotation
}


# Email settings from environment variables

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Use SMTP backend
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')  # Your email address from .env
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # Your email password/app password from .env

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


SPECTACULAR_SETTINGS = {
    'TITLE': '🚀 Space Zone API',
    'DESCRIPTION': """
🌌 **Welcome to Space Zone API**  

Navigate your **digital universe** with speed and security.  
All authentication is handled via **JWT tokens** (Access & Refresh) for seamless access.

---

### 🔑 User Authentication
- `/api/auth/send-code/` — Send login codes to users
- `/api/auth/verify-code/` — Verify user login codes
- `/api/refresh/` — Refresh JWT tokens
- `/api/auth/panel/` — User profile and settings
- `/api/auth/forget/` — Send password reset code
- `/api/auth/forget/set/` — Update password

### 🛡️ Admin Authentication
- `/api/admin/send-code/` — Send admin login codes
- `/api/admin/verify-code/` — Verify admin login codes
- `/api/admin/panel/` — Admin dashboard overview

### 👥 Admin User Management
- `/api/admin/panel/users/` — List all normal users (GET)
- `/api/admin/panel/users/{id}/` — Retrieve or partially update a user (GET/PATCH)
- `/api/admin/panel/users/user_delete/` — Soft delete multiple users (POST)
- ❌ POST (create), PUT (update full), DELETE (destroy) are disabled for users in `UserInformationViewSet`
- ✅ PATCH allowed for partial updates, POST `user_delete` for soft deletion

### 📦 Admin Product Management
- `/api/admin/panel/product/` — List and create products
- `/api/admin/panel/product/{id}/` — Partial update or soft delete a product (PATCH/DELETE)
- `/api/admin/panel/product/delete/` — Soft delete multiple products (POST)

### 🏷️ Admin Category Management
- `/api/admin/panel/category/` — List and create categories
- `/api/admin/panel/category/{id}/` — Partial update or delete a category (PATCH/DELETE)
- `/api/admin/panel/category/delete/` — Soft delete multiple categories (POST)
- `/api/admin/category/select/` — Retrieve categories without children for dynamic select boxes in frontend
- Supports optional `?search=<query>` for autocomplete/dynamic filtering

### 💡 Frontend Notes
- Use `/api/admin/category/select/` for dynamic select box in product forms
- Supports search for large number of categories (autocomplete)
- Pagination handled for users, products, and comments endpoints
- Soft delete is implemented instead of hard delete for safety

**Responses Summary:**
- 200 ✅ success
- 400 ❌ validation error or missing IDs
- 401/403 ❌ unauthorized
- 405 ❌ method not allowed

**Version:** 1.0.0 — Clean, fast, and ready for stellar integrations.

Explore, integrate, and **own your Space Zone**.
""",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': True,

    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'displayRequestDuration': True,
        'filter': True,
        'docExpansion': 'none',
        'persistAuthorization': True,
    },

    'REDOC_SETTINGS': {
        'expandResponses': '200,201',
        'hideDownloadButton': False,
        'expandSingleSchemaField': True,
        'scrollYOffset': 50,
    },

    'SECURITY': [
        {'BearerAuth': []},
    ],

    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': True,
    'SORT_TAGS': 'alpha',
}

